linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - github.com/mmcloughlin/profile
          - $gostd

  lll:
    line-length: 140
    tab-width: 4

issues:
  exclude-use-default: false
  exclude:
    # gosec: G304: Potential file inclusion via variable.
    - G304
