#!/usr/bin/env bash

set -exuo pipefail

# Install golangci-lint
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b "${GOPATH}/bin" v1.39.0

# Install tools.
go install github.com/campoy/embedmd@v1.0.0
