#!/usr/bin/env bash

set -exuo pipefail

# Install golangci-lint
golangci_lint_version='v1.56.1'
golangci_install_script="https://raw.githubusercontent.com/golangci/golangci-lint/${golangci_lint_version}/install.sh"
curl -sfL "${golangci_install_script}" | sh -s -- -b "$GOPATH/bin" "${golangci_lint_version}"

# Install tools.
go install github.com/campoy/embedmd@v1.0.0
