#!/usr/bin/env bash

set -exuo pipefail

# Generate example output.
for example in ./internal/example/*; do
    name=$(basename "${example}")

    # Compile
    bindir=$(mktemp -d)
    go build -o "${bindir}/${name}" "${example}"

    for script in ${example}/*.sh; do
        root="${script%.sh}"
        PATH="${bindir}:${PATH}" bash "${script}" > "${root}.out" 2> "${root}.err"
    done

    # Cleanup
    rm -r "${bindir}"
done
# bash ./internal/examples/cli/cmd.sh 2>&1 | tee ./internal/examples/cli/output

# Generate README.
embedmd -w README.md
